### ISSUE TITLE
Upgrade to React 16 (and other deps)

### ISSUE THREAD

**Issue by jasonmorita** [jasonmorita/react-redux-ui-state#6]
Need to upgrade and test.

**Comment by toomuchdesign** [comment]
I'd suggest to move `react`, `react-redux` and `redux` as peerDependencies, too.

**Comment by jasonmorita** [comment]
@toomuchdesign I completely agree. I have not had time to do this however. There was one PR previously to do this, but it broke all the tests.

If you have time, please submit a PR and we can make this change as it's the right way to go IMO.

Thank you!

**Comment by jasonmorita** [comment]
@solo474 @toomuchdesign Please give it a try. I made some time this morning. Thanks for your patience.

**Comment by toomuchdesign** [comment]
Hi @jasonmorita!
Since I understand the library should stay compatible with both `react `15 and 16, `peerDependencies` field should report the minumum necessary version for the library to work. Like:

```js
"peerDependencies": {
    "react": "^15.0.0 || ^16.0.0",
    "redux": "^3.0.0 || ^4.0.0",
    "react-redux": "^4.0.0 || ^5.0.0"
},
```
If project's test or demo requires those peer dependencies, you might also re-declare them as `devDependencies`.

Greetings!

**Comment by jasonmorita** [comment]
Ah I was in a hurry you are right! I will make another PR or you can! Thanks a lot
